---
output: github_document
---

```{r setup}
library(here)
library(tidyverse)
library(glue)
# devtools::install_github("or-house-vis/history")
library(history) 
end_year <- 2019
```


# Gender overall

Compute proportions of each gender:
```{r}
gender_overall <- house_reps_regular %>% 
  group_by(session_year, gender) %>% 
  count() %>%
  ungroup() %>% 
  complete(session_year, gender, fill = list(n = 0)) %>% 
  group_by(session_year) %>% 
  mutate(prop = n/sum(n),
    gender = gender %>% factor(levels = c("Male", "Female"))
    ) %>% 
  ungroup() 
```

Add captions
```{r}
overall_captions <- gender_overall %>% 
  filter(gender == "Female") %>% 
  select(session_year, n, prop) %>% 
  mutate(caption = 
      glue('<strong>{ session_year }</strong><br />{ round(prop, 2) * 100 }% ({ n } seats) held by females')
    ) %>% 
  select(session_year, caption)
```

Add captions and make sure `session_year` is a date
```{r}
gender_overall <- gender_overall %>%  
  left_join(overall_captions) %>% 
  mutate(
    session_year = ISOdate(year = session_year, 
      month = 1, day = 1, tz = "utc")
  )
```

```{r}
gender_overall_captioned <- 
  gender_overall %>% 
  mutate(session_year = lubridate::year(session_year))
```

Extra data for tooltip layer
```{r}
gender_overall_captioned <- 
  gender_overall_captioned %>% 
  group_by(gender) %>% 
  mutate(
    last_session = lag(session_year, default = 1860),
    next_session = lead(session_year, default = !!end_year + 1),
    x = session_year - (session_year - last_session)/2,
    x2 = session_year + (next_session - session_year)/2
  ) %>% 
  select(-last_session, -next_session)
```


Examine changes
```{r, eval = FALSE}
library(daff)
old <- read_csv(here("docs", "data", "vega-gender-overall.csv"))
diffs <- diff_data(old, gender_overall_captioned, ordered = FALSE)
render_diff(diffs)
```

```{r}
gender_overall_captioned %>% 
  write_csv(here("docs", "data", "vega-gender-overall.csv"))
```

# Gender by party

```{r}
gender_by_party <- house_reps_regular %>% 
  group_by(session_year, party, gender) %>% 
  count() %>%
  ungroup() %>% 
  complete(session_year, party, gender, fill = list(n = 0)) %>% 
  group_by(session_year, party) %>% 
  mutate(
    total = sum(n),
    prop = n/total
    ) %>% 
  filter(party %in% c("Democrat", "Republican")) %>% 
  filter(gender == "Female") %>% 
  ungroup() 
```

Add captions
```{r}
party_captions <- gender_by_party %>% 
  select(session_year, n, total, prop, party) %>% 
  gather("type", "value", -session_year, -party) %>% 
  unite("party_type", party, type) %>% 
  spread(party_type, value) %>% 
  mutate(caption = glue(
    "<strong>{ session_year }</strong><br />{round(Democrat_prop, 2)*100}%  of Democrats ({ Democrat_n }/{ Democrat_total } seats) and <br />{ round(Republican_prop, 2)*100 }%  of Republicans ({ Republican_n }/{ Republican_total } seats) are female.")
  ) %>% 
  select(session_year, caption)
```

Weird captions
```{r}
party_captions <- party_captions %>% 
  mutate(
    caption = ifelse(session_year %in% c(1887, 1889, 1891),
      glue("<strong>{session_year}</strong> Party affiliations unknown."),
      caption
    )
  )
```


```{r}
gender_by_party_captioned <- gender_by_party %>% 
  left_join(party_captions) %>% 
  mutate(
    session_year = ISOdate(year = session_year, 
      month = 1, day = 1, tz = "utc")
  ) %>% 
  mutate(session_year = lubridate::year(session_year))
```

Examine changes
```{r, eval = FALSE}
library(daff)
old <- read_csv(here("docs", "data", "vega-gender-by-party.csv"))
diffs <- diff_data(old, gender_by_party_captioned, ordered = FALSE)
render_diff(diffs)
```

```{r}
gender_by_party_captioned %>% 
  write_csv(here("docs", "data", "vega-gender-by-party.csv"))
```




