---
output: github_document
---

```{r setup}
library(history)
library(tidyverse)
library(jsonlite)
library(here)
```

```{r}
end_year <- 2019
```

## Common pieces

Common config:
```{r spec-common}
spec_common <- list(
  `$schema` = "https://vega.github.io/schema/vega-lite/v3.0.0-rc1.json",
  autosize = list(type = "fit", contains = "padding"),
  config = list(style = list(cell = list(stroke = "transparent"))))
```

Common time axis:
```{r session-year-axis}
session_year_axis <- function(field){
  list(
    field = field,
    type = "quantitative",
    axis = list(
      title = "",
      values = c(1860, seq(1875, end_year, by = 25), end_year),
      grid = FALSE,
      format = "4.0f"
    ),
    scale = list(
      domain = list(1860, end_year),
      nice = FALSE
    )
  )
}
```

Proportions on the y-axis:
```{r proportion-axis}
proportion_axis <- function(title, stack = NULL, opacity = 1) {
  list(
      field = "prop",
      type = "quantitative",
      scale = list(
        domain = list(0, 1)
      ),
      stack = stack,
      axis = list(
        values = seq(0, 1, .25),
        format = "%",
        title = title,
        ticks = FALSE,
        labelPadding = 5,
        domainOpacity = opacity
      )
    )
}
```

Time indication line
```{r}
year_selection <- 
  list(
      brush = list(
        type = "single",
        on = "mouseover",
        encodings = list("x"),
        resolve = "global",
        empty = "none"
        )
      )

time_selection_line <- list(
  transform = list(
    list(
      filter = list(
        selection = "brush")
    )
  ),
  mark = "rule",
  encoding = list(
    x = session_year_axis("session_year"),
    y = NULL,
    color = list(
      value = "#333333"
    ),
    opacity = list(
      value = 1
    ),
    tooltip = list(
      value = NULL
    )
  )
)
```

## Gender Overall
```{r overall_color}
overall_color <- 
  list(
    field = "gender",
    type = "nominal",
    scale = list(
      domain = c("Female", "Male"), 
      range = c("#6F50A1", "#AAC8BD")
    ),
    legend = NULL
  )
```

### Annotations
Annotation data
```{r}
anno <- tribble(
  ~ gender, ~ session_year, ~ prop,
  "Male"  ,           1865,    0.95,
  "Female",           2013,    0.05
) 
```

Annotation layers
```{r}
annotation_layer <- function(data, label, align = "left", baseline = "top", color = "black", opacity = 0.5){
  list(
    data = list(
      values = pmap(data, list)
    ),
    mark = list(
      type = "text",
      size = 20,
      align = align,
      baseline = baseline
    ),
    encoding = list(
      text = list(
        value = label
      ),
      color = list(
        value = color
      ),
      opacity = list(
        value = opacity
      )
    )
  )
}

male_anno <- annotation_layer(anno[1, ], "Male")
female_anno <- annotation_layer(anno[2, ], "Female",
  color = "white", align = "right", baseline = "bottom")
```


```{r gender-overall}
gender_plot <- list(
  encoding = list(
    x = session_year_axis("session_year"),
    y = proportion_axis("Percentage of house seats", stack = "zero",
      opacity = 0),
    color = overall_color,
    opacity = list(
      value = 0.8
    ),
    order = list(
      field = "gender_order",
      type = "ordinal"
    ),
    tooltip = list(
      value = NULL
    )
  ),
  transform = list(
    list(
      calculate = "if(datum.gender == 'Female', 0, 1)",
      as = "gender_order"
    )
  ),
  layer = list(
    list(
      selection = year_selection,
      mark = "area"
    ),
    male_anno,
    female_anno,
    time_selection_line,
    list(
      mark = list(
        type = "bar"
      ),
      encoding = list(
        x = session_year_axis("x"),
        x2 = session_year_axis("x2"),
        opacity = list(
          value = 0
        ),
        tooltip = list(
          field = "caption",
          type = "nominal"
        )
      )
    )
  )
)  

overall_params <- list(
  data = list(url = "data/vega-gender-overall.csv"), 
  description = "Gender breakdown in house over time"
)

spec_common %>% 
  c(overall_params) %>% 
  c(gender_plot) %>% 
  write_json(here("docs", "spec-overall.json"), 
  auto_unbox = TRUE, pretty = TRUE, null = "null")
```

## Gender by party

```{r}
party_params <- list(
    data = list(url = "data/vega-gender-by-party.csv"), 
    description = "Gender breakdown by party in house over time"
  )
```


### Annotation
```{r}
anno_party <- tribble(
  ~ session_year,          ~ party,  ~ prop,    ~ label,
            2019,       "Democrat",    0.60, "Democrats",
            2019,     "Republican",    0.05, "Republicans",
)
```


Annotation layer
```{r}
annotation_layer_party <- function(data){
  list(
    data = list(
      values = pmap(data, list)
    ),
    mark = list(
      type = "text",
      align = "right",
      dx = 0
    ),
    encoding = list(
      text = list(
        field = "label",
        type = "nominal"
      ),
      y = list(
        stack = NULL,
        field = "prop",
        type = "quantitative"
      )
    )
  )
}

anno_party_layer <- annotation_layer_party(anno_party)
```


```{r gender-by-party}
gender_by_party_plot <- list(
  encoding = list(
    x = session_year_axis("session_year"),
    y = proportion_axis("Percentage of party seats", stack = NULL),
    color = list(
      field = "party",
      type = "nominal",
      scale = list(
        domain = list("Democrat", "Republican"),
        range = list("#377EB8", "#E41A1C")
      ),
      legend = NULL
    ),
    tooltip = list(
      value = NULL
    )
  ),
  layer = list(
    list(
      mark = "line"
    ),
    list(
      mark = "point",
      selection = year_selection,
      encoding = list(
        opacity = list(
          value = 0
        )
      )
    ),
    anno_party_layer, 
    time_selection_line,
    list(
      mark = list(
        type = "bar"
      ),
      encoding = list(
        y = list(field = "y", type = "quantitative"),
        x = list(field = "x", type = "quantitative"),
        x2 = list(field = "x2", type = "quantitative"),
        opacity = list(
          value = 0
        ),
        tooltip = list(
          field = "caption",
          type = "nominal"
        )
      )
    )
  )
)  

spec_common %>% 
  c(party_params) %>% 
  c(gender_by_party_plot) %>% 
  write_json(here("docs", "spec-by-party.json"), 
  auto_unbox = TRUE, pretty = TRUE, null = "null")
```